<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
    <StartupObject>Showcase.Program</StartupObject>
    <AssemblyName>ClShowcase</AssemblyName>
    <NoWarn>$(NoWarn);CS8602;CS8604;CS8600;CS8618</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\CloudLauncher\CloudLauncher.csproj" />
  </ItemGroup>
</Project>
