using System.IO;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Threading;
using CloudLauncher.Services;
using CloudLauncher.Shared;
using Microsoft.Web.WebView2.Core;
using Microsoft.Web.WebView2.Wpf;

namespace CloudLauncher.Views;

/// <summary>
/// Read-only rich-description viewer backed by WebView2, used by the mod, resource-pack, world and
/// pack browse pages. It renders the HTML <see cref="PackText.WrapHtmlDocument"/> produces;
/// <see cref="RichDescriptionEditor"/> is the editing counterpart.
///
/// WebView2 is a native ("airspace") surface that can't follow a WPF RenderTransform, so during a
/// page or tab slide it would stay put and jump at the end. While an ancestor transition runs, a
/// bitmap snapshot of the last frame is shown in its place and slides normally, then the live
/// surface comes back.
/// </summary>
public sealed class RichDescriptionView : UserControl, IDisposable
{
    // A per-user writable folder is required; the default (next to the exe) is read-only
    // once the launcher is installed under Program Files.
    private static readonly string UserDataFolder = Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
        "CloudLauncher", "WebView2");

    private readonly WebView2 _web = new();
    // Overlay shown during a transition: the last rendered frame, which slides with the animation.
    private readonly Image _snapshot = new() { Stretch = Stretch.Fill, Visibility = Visibility.Collapsed };
    private readonly DispatcherTimer _revealTimer = new();

    private bool _initStarted;
    private bool _ready;
    /// <summary>NavigateToString calls whose navigation has not started yet. Only those loads may
    /// replace the document; anything the page itself starts is cancelled.</summary>
    private int _ownNavigationsPending;
    private bool _disposed;
    private bool _transitionActive;
    private string? _pendingHtml;
    private string? _lastHtml;
    private RichDescriptionOptions? _options;

    public RichDescriptionView()
    {
        // Paint the document background underneath so there's no white flash before the
        // first frame renders (matches the body colour in WrapHtmlDocument, whatever the theme).
        ApplyThemeBackground();
        _web.NavigationStarting += OnNavigationStarting;
        _web.NavigationCompleted += OnNavigationCompleted;
        _web.CoreWebView2InitializationCompleted += OnCoreInitialized;

        var grid = new Grid();
        grid.Children.Add(_web);
        grid.Children.Add(_snapshot); // overlays the web view while a transition slides
        Content = grid;

        // Show a blank document until the first real Show() so the panel isn't an empty void.
        _pendingHtml = PackText.WrapHtmlDocument("<p><em>No description.</em></p>", legacyIe: false);
        _lastHtml = _pendingHtml;

        _revealTimer.Tick += OnRevealTimerTick;
        Loaded += OnLoaded;
        Unloaded += OnUnloaded;
        Services.ThemeService.Changed += OnThemeChanged;
    }

    /// <summary>
    /// Theme changes don't repaint a web document, so the HTML is regenerated by re-showing the same
    /// content.
    /// </summary>
    private void OnThemeChanged()
    {
        if (!Dispatcher.CheckAccess()) { Dispatcher.BeginInvoke(OnThemeChanged); return; }
        if (_disposed) return;
        ApplyThemeBackground();
        if (_lastContent is not null) Show(_lastContent, _lastIsMarkdown, _options);
    }

    private void ApplyThemeBackground()
    {
        var hex = PackText.HtmlPalette.Current.Background;
        try
        {
            var colour = (Color)ColorConverter.ConvertFromString(hex);
            Background = new SolidColorBrush(colour);
            _web.DefaultBackgroundColor = System.Drawing.Color.FromArgb(0xFF, colour.R, colour.G, colour.B);
        }
        catch { /* a malformed colour must not take the panel down */ }
    }

    private string? _lastContent;
    private bool _lastIsMarkdown;

    private void OnLoaded(object sender, RoutedEventArgs e)
    {
        Animations.Animate.AirspaceTransitionChanged -= OnAirspaceTransitionChanged; // avoid double-subscribe
        Animations.Animate.AirspaceTransitionChanged += OnAirspaceTransitionChanged;
        MainWindow.DialogStackChanged -= OnDialogStackChanged;
        MainWindow.DialogStackChanged += OnDialogStackChanged;
        // If we loaded into a transition already in flight, cover with the snapshot immediately.
        if (Animations.Animate.IsTransitionActiveFor(this)) BeginTransitionOverlay();
        if (MainWindow.IsUnderCard(this)) OnOverlayChanged(true);
        EnsureWebViewInitialized();
    }

    private void OnUnloaded(object sender, RoutedEventArgs e)
    {
        Animations.Animate.AirspaceTransitionChanged -= OnAirspaceTransitionChanged;
        MainWindow.DialogStackChanged -= OnDialogStackChanged;
        _revealTimer.Stop();
    }

    private bool _overlayCover;

    /// <summary>A card or dialog opened or closed somewhere in the window.</summary>
    /// <remarks>Asks whether one is over this view rather than whether any is up: a view on a card
    /// (the update review, the version picker, a changelog card) must keep showing on it.</remarks>
    private void OnDialogStackChanged() => OnOverlayChanged(MainWindow.IsUnderCard(this));

    /// <summary>
    /// A card or dialog is over the view. The native surface would paint over it, so it hides behind
    /// its snapshot (or the panel background, if nothing has rendered) until the overlay closes.
    /// </summary>
    private void OnOverlayChanged(bool visible)
    {
        _overlayCover = visible;
        if (visible)
        {
            if (_snapshot.Source is not null) _snapshot.Visibility = Visibility.Visible;
            _web.Visibility = Visibility.Hidden;
        }
        else if (!_transitionActive)
        {
            _web.Visibility = Visibility.Visible;
            _snapshot.Visibility = Visibility.Collapsed;
        }
    }

    /// <summary>Render a description (HTML or markdown) into the view.</summary>
    public void Show(string? content, bool isMarkdown = false, RichDescriptionOptions? options = null)
    {
        _lastContent = content;
        _lastIsMarkdown = isMarkdown;
        _options = options;
        var runnable = options?.EnableCommandRun == true;

        string html;
        if (string.IsNullOrWhiteSpace(content))
        {
            html = PackText.WrapHtmlDocument("<p><em>No description.</em></p>", legacyIe: false);
        }
        else
        {
            var body = PackText.PrepareDescriptionHtml(content, isMarkdown, runnable);
            html = PackText.WrapHtmlDocument(body, runnableCommands: runnable, legacyIe: false);
        }

        _lastHtml = html;
        if (_ready)
            NavigateOwn(html);
        else
        {
            _pendingHtml = html;
            EnsureWebViewInitialized();
        }
    }

    // ── transition handling (airspace-safe slide) ─────────────────────────────

    private void OnAirspaceTransitionChanged()
    {
        if (Animations.Animate.IsTransitionActiveFor(this))
            BeginTransitionOverlay();
    }

    /// <summary>Cover the live surface with the (sliding) snapshot for the rest of the transition.</summary>
    private void BeginTransitionOverlay()
    {
        if (_snapshot.Source is not null)
        {
            _snapshot.Visibility = Visibility.Visible;
            _web.Visibility = Visibility.Hidden;
        }
        _transitionActive = true;
        _revealTimer.Stop();
        _revealTimer.Interval = TimeSpan.FromMilliseconds(Math.Max(1, Animations.Animate.TransitionRemainingMs));
        _revealTimer.Start();
    }

    private void OnRevealTimerTick(object? sender, EventArgs e)
    {
        _revealTimer.Stop();
        // A newer transition may have started while this one was settling; keep covering if so.
        if (Animations.Animate.IsTransitionActiveFor(this)) { BeginTransitionOverlay(); return; }
        _transitionActive = false;
        if (_overlayCover) return;   // still under a card: stays covered until it closes
        _web.Visibility = Visibility.Visible;
        _snapshot.Visibility = Visibility.Collapsed;
    }

    private void OnNavigationCompleted(object? sender, CoreWebView2NavigationCompletedEventArgs e)
    {
        if (!_transitionActive && !_overlayCover) _web.Visibility = Visibility.Visible;
        _ = CaptureSnapshotAsync();
    }

    /// <summary>Grab the current rendered frame so a subsequent transition has something to slide.</summary>
    private async Task CaptureSnapshotAsync()
    {
        if (_web.CoreWebView2 is null) return;
        try
        {
            using var ms = new MemoryStream();
            await _web.CoreWebView2.CapturePreviewAsync(CoreWebView2CapturePreviewImageFormat.Png, ms);
            ms.Position = 0;
            var bmp = new BitmapImage();
            bmp.BeginInit();
            bmp.CacheOption = BitmapCacheOption.OnLoad;
            bmp.StreamSource = ms;
            bmp.EndInit();
            bmp.Freeze();
            _snapshot.Source = bmp;
        }
        catch { /* snapshot is best-effort; without it a transition just hides the surface */ }
    }

    // ── WebView2 plumbing ─────────────────────────────────────────────────────

    private void NavigateOwn(string html)
    {
        // Capped, because a load superseded before it starts never reports back.
        _ownNavigationsPending = Math.Min(_ownNavigationsPending + 1, 4);
        _web.NavigateToString(html);
    }

    private async void EnsureWebViewInitialized()
    {
        if (_initStarted || _disposed) return;
        _initStarted = true;
        try
        {
            Directory.CreateDirectory(UserDataFolder);
            var env = await CoreWebView2Environment.CreateAsync(null, UserDataFolder, null);
            await _web.EnsureCoreWebView2Async(env);
        }
        catch (Exception ex)
        {
            // Leave _initStarted set: a retry would almost certainly hit the same fault
            // (missing WebView2 runtime, locked profile). Surface it in the log instead.
            AppLog.LogError("WebView2", ex);
        }
    }

    private void OnCoreInitialized(object? sender, CoreWebView2InitializationCompletedEventArgs e)
    {
        if (!e.IsSuccess || _web.CoreWebView2 is null)
        {
            if (e.InitializationException is { } ex)
                AppLog.LogError("WebView2", ex);
            return;
        }

        DescriptionWebView.Harden(_web.CoreWebView2);
        var s = _web.CoreWebView2.Settings;
        s.AreDefaultContextMenusEnabled = false;
        s.AreBrowserAcceleratorKeysEnabled = false;
        // Nothing in the read-only page talks to the launcher.
        s.IsWebMessageEnabled = false;

        _web.CoreWebView2.NewWindowRequested += OnNewWindowRequested;

        _ready = true;
        if (_pendingHtml is { } html)
        {
            _pendingHtml = null;
            NavigateOwn(html);
        }
    }

    // Only our own NavigateToString document (a data:text/html URL) is allowed. Everything else is
    // cancelled: a clicked command link fires the command callback, other clicked http(s) links open
    // in the real browser, and navigations the page starts itself open nothing.
    private void OnNavigationStarting(object? sender, CoreWebView2NavigationStartingEventArgs e)
    {
        var uri = e.Uri ?? "";
        if (uri.Equals("about:blank", StringComparison.OrdinalIgnoreCase)) return;   // an empty page
        if (_ownNavigationsPending > 0 && uri.StartsWith("data:text/html", StringComparison.OrdinalIgnoreCase))
        {
            _ownNavigationsPending--;
            return;
        }

        e.Cancel = true;
        if (!e.IsUserInitiated) return;

        if (PackText.TryParseCommandRunUri(uri, out var command))
        {
            if (_options?.EnableCommandRun == true)
                _options.OnCommandRun?.Invoke(command);
            return;
        }

        OpenExternally(uri);
    }

    private void OnNewWindowRequested(object? sender, CoreWebView2NewWindowRequestedEventArgs e)
    {
        e.Handled = true;
        if (e.IsUserInitiated) OpenExternally(e.Uri);
    }

    // SafeLaunch opens http and https only; anything else a link points at is dropped.
    private static void OpenExternally(string? uri) => SafeLaunch.OpenUrl(uri);

    /// <summary>Releases the native browser host. Optional, since the control is collectible once its
    /// page is discarded; hosts may call it for prompt cleanup (e.g. a browse window closing).</summary>
    public void Dispose()
    {
        Services.ThemeService.Changed -= OnThemeChanged;
        if (_disposed) return;
        _disposed = true;
        Animations.Animate.AirspaceTransitionChanged -= OnAirspaceTransitionChanged;
        MainWindow.DialogStackChanged -= OnDialogStackChanged;
        _revealTimer.Stop();
        _web.NavigationStarting -= OnNavigationStarting;
        _web.NavigationCompleted -= OnNavigationCompleted;
        _web.CoreWebView2InitializationCompleted -= OnCoreInitialized;
        if (_web.CoreWebView2 is not null)
            _web.CoreWebView2.NewWindowRequested -= OnNewWindowRequested;
        _web.Dispose();
    }
}

/// <summary>Settings and refusals shared by the description viewer and editor. Both show text other
/// people wrote, so neither may download, hand a link to another program, grant a permission, load a
/// frame, show a sign-in prompt or reach the launcher through host objects.</summary>
/// <remarks>The handlers capture nothing, so they do not keep the control alive and need no
/// unsubscribing.</remarks>
internal static class DescriptionWebView
{
    public static void Harden(CoreWebView2 core)
    {
        var s = core.Settings;
        s.AreDevToolsEnabled = false;
        s.AreHostObjectsAllowed = false;
        s.IsStatusBarEnabled = false;
        s.IsZoomControlEnabled = false;
        s.IsPasswordAutosaveEnabled = false;
        s.IsGeneralAutofillEnabled = false;
        core.PermissionRequested += (_, e) => e.State = CoreWebView2PermissionState.Deny;
        core.FrameNavigationStarting += (_, e) => e.Cancel = true;

        // Newer runtime interfaces: an older WebView2 runtime throws for these, and the rest of the
        // setup must still happen.
        Try(() => s.IsSwipeNavigationEnabled = false);
        Try(() => core.DownloadStarting += (_, e) => { e.Cancel = true; e.Handled = true; });
        Try(() => core.BasicAuthenticationRequested += (_, e) => e.Cancel = true);
        Try(() => core.LaunchingExternalUriScheme += (_, e) => e.Cancel = true);
    }

    private static void Try(Action apply)
    {
        try { apply(); }
        catch (Exception ex) { AppLog.Log("WebView2", $"A description setting is not available on this runtime: {ex.Message}"); }
    }
}
